SELECT * FROM PRODUCTS;
DROP TABLE PRODUCTS;

DESC PRODUCTS;

CREATE TABLE PRODUCTS(
PRODUCT_ID    VARCHAR2(255 CHAR) NOT NULL ,
PRODUCT_NAME  VARCHAR2(255 CHAR) 
);

insert into PRODUCTS (PRODUCT_NAME, PRODUCT_ID) values (?, ?);
insert into PRODUCTS (PRODUCT_NAME, PRODUCT_ID) values ('P02','SPRING');